#Wed Aug 28 05:21:18 BST 2024
micronaut:
  application:
    name: micronautdemo
  metrics:
    enabled: true
  security:
    authentication: bearer
    jwt-auth:
      user: ${jwt-auth-user}
      password: ${jwt-auth-password}